name: Run lint and tests
on: 
  push

jobs:
    test:
      runs-on: macos-latest
      steps:
       - name: Install code
         uses: actions/checkout@v3

       - name: Install dependencies
         run: npm ci

       - name: Run Tests
         run: npm |
              lint
              test
              build
              
       - name: Deploy
         run: echo "Deploying..."


